on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dispatch:
    name: dispatch to mask-kube repo
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: dispatch to mask-kube
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          curl -u ":${{ secrets.token }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/shigedangao/mask-kube/actions/workflows/deploy_app.yaml/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "tag": "'$git_hash'",
                "app_name": "${{ inputs.app_name }}",
                "env": "${{ inputs.env }}"
              }
            }'
